### ISSUE TITLE
PUT /:courseId/register

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#15]
Start the registration process. Student will provide their student number and labId and will be directed to GitHub for authentication. 

Student registration will only succeed if:

* student number & labid match for student in classlist for course.
* github authentication succeeds and a valid github user is returned.

A second endpoint for receiving the GitHub postLogin will probably also be needed.

**Comment by andrewstec** [comment]
Can I verify that the :courseID/ parameter is intentional in this route?

I think that the logic behind this endpoint is: 

If (A.) a courseID matches, then (B.) if the SNUM and LabID exists under the same user the classList with the courseID, then (C.) we retrieve the Github authentication username and enrol them in a particular course. 

Based on the currently implemented logic by Michael, a CSID is required in addition to a SNUM to check if a user is able to be registered. If the user is able to be registered, then we can take their Github username from the authentication process. 

Do you have a preference over which route we go? I wanted to double-check due to slight differences in the logic here.

Instead of registering for a particular course, it looks like Michael's alternative is that we can check to see if (1.) a User with a CSID and SNUM exist. We can then (2.) tie in their Github information together. Based on the classLists uploaded by the prof, we can then (3.) automatically enrol them in the course.

Much appreciated! I'll continue to look at the other endpoints and see if I can figure this out too.

**Comment by rtholmes** [comment]
We need to know what courseId is going to be used for the session, and what classList to validate the student against, which is why I had courseId in there. You can try what you think works and we can refine if needed.

**Comment by andrewstec** [comment]
I made a new issue to continue on with this issue on the front-end: #21.

This endpoint is done.
