### ISSUE TITLE
Grades can be strings

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#24]
This just cropped up from another course; right now grades can only be 0..100, but some strings are permissible (e.g., 'DNW' for DidNotWrite). I'm not sure how exactly we should handle this (e.g., specify the strings that are allowable), but we should be aware this will crop up.

**Comment by andrewstec** [comment]
Wow. That is a very cryptic bug. It's a great discovery. I will certainly change the model in the schema for the Grade class to accommodate this new possibility. 

I will most likely specify the strings that are allowable or throw an error. 

From what I have been reading about APIs, it is common to throw and catch a bug type when it is foreseeable, which will turn into a particular 500 response. I am trying to anticipate common issues so that I can handle the error. For example, I will throw an "Object already exists" error when someone tries to add an object twice.

I'm not too sure how I will handle these write errors, but this information could be useful. I'll think about how we can accommodate this information. It sounds like super useful information for the user on the front-end, as a TA would like to know when their grade entry fails. 

Did we, by any chance, find out why some grades failed to write?

**Comment by rtholmes** [comment]
From here it looks like Standing Deferred (SD) and Did Not Write (DNW) might be the only two strings allowed for final grades, although maybe just letting it be open ended would be more flexible:

https://science.ubc.ca/sites/science.ubc.ca/files/faculty/teaching/Term_End_Guidelines.pdf

**Comment by andrewstec** [comment]
Ah, I see. Thank you for the context. I misunderstood DNW for a write error to a physical disk. 

This makes perfect sense, and it will be easy to accommodate.

**Comment by rtholmes** [comment]
I think this works as is right now.
